Renamed Flashize-Ext to Flashize-EBB

diff --git a/flashize-ebb b/flashize-ebb
--- a/flashize-ebb
+++ b/flashize-ebb
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #####################################################
-# Flashize-Ext                                      #
+# Flashize-EBB                                      #
 # Copyright 2016, Lanchon                           #
 #####################################################
 
@@ -50,10 +50,12 @@ if [ "$srcdir" == "-" ]; then srcdir=""; fi
 if [ "$destdir" == "-" ]; then destdir=""; fi
 
 if  [ -z "$script" ] || [ -z "$inzip" ] || ([ "$script" == "-" ] && [ -z "$zip" ]) || [ -z "$destdir" ]; then
-    error "Flashize-Ext ($version)"
+    error "Flashize-EBB ($version)"
     error
     error "Converts a shell script to a flashable Android recovery zip. The resulting flashable zip"
     error "can automatically extract resources bundled within the zipfile before invoking the script."
+    error "This tool is incompatible with toybox due to shortcomings of its 'unzip' command, and"
+    error "requires BusyBox instead. Thus the toybox-based CyanogenMod 13 recovery is not supported."
     error
     error "Usage: <input-script> <input-zip> <output-zip> <runtime-logfile> <src-dir> <dest-dir> [<extra-src-spec>...]"
     error
@@ -77,7 +79,7 @@ if  [ -z "$script" ] || [ -z "$inzip" ] || ([ "$script" == "-" ] && [ -z "$zip" 
     error "   <src-dir> there. Also extracts files matching <extra-src-spec> to <dest-dir>."
     error
     error "Script debugging modes are enabled by creating dummy files on the target device:"
-    error "  -Create '/tmp/flashize-ext-debug' to trace the user-supplied script."
+    error "  -Create '/tmp/flashize-ebb-debug' to trace the user-supplied script."
     error "  -Create '/tmp/flashize-debug' to trace resource extraction."
     fatal
 fi
@@ -114,11 +116,11 @@ cp -T "$inzip" "$tmpzip"
 (
     cat <<EOF
 #####################################################
-# Flashize-Ext Runtime (${version})                 #
+# Flashize-EBB Runtime (${version})                #
 # Copyright 2016, Lanchon                           #
 #####################################################
 
-export FLASHIZE_EXT_VERSION='$version'
+export FLASHIZE_EBB_VERSION='$version'
 EOF
     if [ -z "$srcdir" ]; then
         cat <<EOF
@@ -141,10 +143,10 @@ EOF
     echo
     cat <<EOF
 if [ \$? -ne 0 ]; then
-    >&2 echo "flashize-ext: unable to extract package contents"
+    >&2 echo "flashize-ebb: unable to extract package contents"
     exit 1
 fi
-[ ! -f /tmp/flashize-ext-debug ] && set +x || set -x
+[ ! -f /tmp/flashize-ebb-debug ] && set +x || set -x
 
 #####################################################
 
